### ISSUE TITLE
Local Play

### ISSUE THREAD

**Issue by ptmuldoon** [TheBerkin/cards-over-lan#7]
Probably not a bug, but what IP's do you use to play on your LAN?

I left it as localhost, and then try to connect to that PC with 192.168.x.x.:3000 yet can not connect.

Do we need to edit the ws_url or something else?

**Comment by TheBerkin** [comment]
Have you tried just setting host_url to http://127.0.0.1:80? If that still doesn't work, check your local and gateway firewall settings.

**Comment by TheBerkin** [comment]
Since this isn't isn't a bug or feature request, I am closing it. Feel free to submit a separate issue if you find any server bugs relating to LAN play.
